### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by chrisma89** [elismountain/fitness-app#49]
is anyone working on the readme please? happy to work on it if not.

**Comment by SamiraBalayoglu** [comment]
I am working on Readme, will push it soon.

**Comment by chrisma89** [comment]
Thank you.
The warm up video needs to be added to credits section. The link is below
https://www.youtube.com/watch?v=qZkxKTxXY8M

**Comment by chrisma89** [comment]
Also, could add the Collaborators section at the top of the readme and add all our names to it.

**Comment by SamiraBalayoglu** [comment]
Readme file is ready.
